from pathlib import Path

path = Path('ClockTimer.js')
s = path.read_text()

old = '''                    --clock-timer-ring-resize-duration:\n                        333ms;\n\n                    position: relative;'''
new = '''                    --clock-timer-ring-resize-duration:\n                        333ms;\n\n                    --clock-timer-glass-highlight-opacity:\n                        0.72;\n\n                    --clock-timer-glass-vignette-opacity:\n                        0.24;\n\n                    --clock-timer-glass-edge-opacity:\n                        0.28;\n\n                    position: relative;'''
if old not in s:
    raise SystemExit('host variable insertion point not found')
s = s.replace(old, new, 1)

old = '''                #face-background {\n                    position: absolute;\n                    inset: 0;\n                    border-radius: 50%;\n                    z-index: -1;\n                    pointer-events: none;\n                }'''
new = '''                #face-background {\n                    position: absolute;\n                    inset: 0;\n                    border-radius: 50%;\n                    z-index: -1;\n                    overflow: hidden;\n                    pointer-events: none;\n                    box-shadow:\n                        inset 0 0 clamp(12px, 5cqi, 30px)\n                            rgb(0 0 0 / calc(\n                                var(--clock-timer-glass-vignette-opacity) * 0.38\n                            )),\n                        inset 0 clamp(1px, 0.5cqi, 3px) clamp(4px, 1.6cqi, 10px)\n                            rgb(255 255 255 / calc(\n                                var(--clock-timer-glass-edge-opacity) * 0.72\n                            ));\n                }\n\n                #face-background::before,\n                #face-background::after {\n                    content: \"\";\n                    position: absolute;\n                    inset: 0;\n                    border-radius: inherit;\n                    pointer-events: none;\n                }\n\n                #face-background::before {\n                    background:\n                        radial-gradient(\n                            ellipse 74% 48% at 30% 16%,\n                            rgb(255 255 255 / 34%) 0%,\n                            rgb(255 255 255 / 16%) 28%,\n                            transparent 68%\n                        ),\n                        linear-gradient(\n                            145deg,\n                            rgb(255 255 255 / 18%) 0%,\n                            transparent 34%,\n                            transparent 68%,\n                            rgb(255 255 255 / 6%) 100%\n                        );\n                    opacity:\n                        var(--clock-timer-glass-highlight-opacity);\n                    mix-blend-mode: screen;\n                }\n\n                #face-background::after {\n                    background:\n                        radial-gradient(\n                            circle at 50% 43%,\n                            transparent 52%,\n                            rgb(0 0 0 / 8%) 78%,\n                            rgb(0 0 0 / 20%) 100%\n                        ),\n                        linear-gradient(\n                            180deg,\n                            rgb(255 255 255 / 8%) 0%,\n                            transparent 24%,\n                            transparent 72%,\n                            rgb(0 0 0 / 10%) 100%\n                        );\n                    opacity:\n                        var(--clock-timer-glass-vignette-opacity);\n                }'''
if old not in s:
    raise SystemExit('face background block not found')
s = s.replace(old, new, 1)

path.write_text(s)
