from pathlib import Path
p=Path('ClockTimer.js')
s=p.read_text()
old='''                const startTimeMilliseconds =\n                    starts[0].milliseconds;\n\n                const terminal =\n                    ends[0].milliseconds;\n'''
new='''                const lateStarts = [];\n\n                for (let index = 1; index < events.length - 1; index++) {\n                    const event = events[index];\n\n                    if (["start", "resume", "end"].includes(event.type)) {\n                        continue;\n                    }\n\n                    const allowedEntry =\n                        Object.entries(event.attributes)\n                            .find(([name]) =>\n                                name.toLowerCase() === "allowed"\n                            );\n\n                    if (!allowedEntry) {\n                        continue;\n                    }\n\n                    const allowedMinutes =\n                        Number(allowedEntry[1]);\n\n                    if (\n                        !Number.isFinite(allowedMinutes) ||\n                        allowedMinutes < 0\n                    ) {\n                        return false;\n                    }\n\n                    const next = events[index + 1];\n\n                    if (next?.type !== "resume") {\n                        continue;\n                    }\n\n                    const allowedEnd =\n                        event.milliseconds +\n                        allowedMinutes * ClockTimer.#MINUTE;\n\n                    if (next.milliseconds > allowedEnd) {\n                        lateStarts.push({\n                            start: allowedEnd,\n                            end: next.milliseconds\n                        });\n                    }\n                }\n\n                const startTimeMilliseconds =\n                    starts[0].milliseconds;\n\n                const terminal =\n                    ends[0].milliseconds;\n'''
if old not in s: raise SystemExit('late start anchor not found')
s=s.replace(old,new,1)
old2='''                    this.#refreshRingLayout(\n                        terminal,\n                        {\n                            refreshTickMarks: true\n                        }\n                    );\n'''
new2='''                    for (const lateStart of lateStarts) {\n                        let cursor = lateStart.start;\n\n                        while (cursor < lateStart.end) {\n                            const ringIndex =\n                                this.#getRingIndex(cursor);\n\n                            const segmentEnd =\n                                Math.min(\n                                    lateStart.end,\n                                    this.#getRingStart(ringIndex) +\n                                        ClockTimer.#HOUR\n                                );\n\n                            const ring =\n                                this.#ensureRing(ringIndex);\n\n                            const range =\n                                this.#createTimeRange(\n                                    "prestart",\n                                    cursor,\n                                    segmentEnd\n                                );\n\n                            range.setAttribute(\n                                "overlapping",\n                                ""\n                            );\n\n                            ring.appendChild(range);\n\n                            cursor = segmentEnd;\n                        }\n                    }\n\n                    this.#refreshRingLayout(\n                        terminal,\n                        {\n                            refreshTickMarks: true\n                        }\n                    );\n'''
if old2 not in s: raise SystemExit('refresh anchor not found')
s=s.replace(old2,new2,1)
p.write_text(s)
