from pathlib import Path
p=Path('TimeRange.js')
s=p.read_text()
needle='''        if (mode !== "radial") {\n            const startProgress ='''
replacement='''        if (mode !== "radial") {\n            const parentStyle =\n                getComputedStyle(parent);\n\n            const paddingLeft =\n                Number.parseFloat(parentStyle.paddingLeft) || 0;\n\n            const paddingRight =\n                Number.parseFloat(parentStyle.paddingRight) || 0;\n\n            const paddingTop =\n                Number.parseFloat(parentStyle.paddingTop) || 0;\n\n            const paddingBottom =\n                Number.parseFloat(parentStyle.paddingBottom) || 0;\n\n            const contentWidth =\n                Math.max(\n                    0,\n                    width -\n                        paddingLeft -\n                        paddingRight\n                );\n\n            const contentHeight =\n                Math.max(\n                    0,\n                    height -\n                        paddingTop -\n                        paddingBottom\n                );\n\n            const startProgress ='''
if needle not in s: raise SystemExit('mode block not found')
s=s.replace(needle,replacement,1)
s=s.replace('''                const startX =\n                    width * startProgress;\n\n                const endX =\n                    width * endProgress;''','''                const startX =\n                    paddingLeft +\n                    contentWidth * startProgress;\n\n                const endX =\n                    paddingLeft +\n                    contentWidth * endProgress;''',1)
s=s.replace('''                    { x: startX, y: 0 },\n                    { x: endX, y: 0 },\n                    { x: endX, y: height },\n                    { x: startX, y: height }''','''                    { x: startX, y: paddingTop },\n                    { x: endX, y: paddingTop },\n                    { x: endX, y: paddingTop + contentHeight },\n                    { x: startX, y: paddingTop + contentHeight }''',1)
s=s.replace('''                const startX =\n                    width *\n                    (1 - startProgress);\n\n                const endX =\n                    width *\n                    (1 - endProgress);''','''                const startX =\n                    paddingLeft +\n                    contentWidth *\n                        (1 - startProgress);\n\n                const endX =\n                    paddingLeft +\n                    contentWidth *\n                        (1 - endProgress);''',1)
s=s.replace('''                    { x: startX, y: 0 },\n                    { x: endX, y: 0 },\n                    { x: endX, y: height },\n                    { x: startX, y: height }''','''                    { x: startX, y: paddingTop },\n                    { x: endX, y: paddingTop },\n                    { x: endX, y: paddingTop + contentHeight },\n                    { x: startX, y: paddingTop + contentHeight }''',1)
s=s.replace('''                const startY =\n                    height * startProgress;\n\n                const endY =\n                    height * endProgress;''','''                const startY =\n                    paddingTop +\n                    contentHeight * startProgress;\n\n                const endY =\n                    paddingTop +\n                    contentHeight * endProgress;''',1)
s=s.replace('''                    { x: 0, y: startY },\n                    { x: width, y: startY },\n                    { x: width, y: endY },\n                    { x: 0, y: endY }''','''                    { x: paddingLeft, y: startY },\n                    { x: paddingLeft + contentWidth, y: startY },\n                    { x: paddingLeft + contentWidth, y: endY },\n                    { x: paddingLeft, y: endY }''',1)
s=s.replace('''            const startY =\n                height *\n                (1 - startProgress);\n\n            const endY =\n                height *\n                (1 - endProgress);''','''            const startY =\n                paddingTop +\n                contentHeight *\n                    (1 - startProgress);\n\n            const endY =\n                paddingTop +\n                contentHeight *\n                    (1 - endProgress);''',1)
s=s.replace('''                { x: 0, y: startY },\n                { x: width, y: startY },\n                { x: width, y: endY },\n                { x: 0, y: endY }''','''                { x: paddingLeft, y: startY },\n                { x: paddingLeft + contentWidth, y: startY },\n                { x: paddingLeft + contentWidth, y: endY },\n                { x: paddingLeft, y: endY }''',1)
p.write_text(s)
