from pathlib import Path

p=Path('ClockTimer.js')
s=p.read_text()
clear='''            this.#tickMarkLayer.replaceChildren();'''
if s.count(clear)!=1: raise SystemExit(f'clear count {s.count(clear)}')
s=s.replace(clear,'''            const previousTrailing =\n                this.#tickMarkLayer.firstElementChild;''',1)
old='''            this.#tickMarkLayer.appendChild(\n                fragment\n            );'''
new='''            if (\n                mode === "+/-5"\n            ) {\n                const tracks =\n                    Array.from(\n                        fragment.children\n                    );\n\n                const leading =\n                    tracks.at(-1);\n\n                if (leading) {\n                    leading.animate(\n                        [\n                            { opacity: 0 },\n                            { opacity: 1 }\n                        ],\n                        {\n                            duration: 1000 / 3,\n                            easing: "linear",\n                            fill: "both"\n                        }\n                    );\n                }\n\n                if (previousTrailing) {\n                    const clone =\n                        previousTrailing.cloneNode(\n                            true\n                        );\n\n                    this.#tickMarkLayer.replaceChildren(\n                        clone\n                    );\n\n                    clone.animate(\n                        [\n                            { opacity: 1 },\n                            { opacity: 0 }\n                        ],\n                        {\n                            duration: 1000 / 3,\n                            easing: "linear",\n                            fill: "forwards"\n                        }\n                    ).finished\n                        .finally(\n                            () => clone.remove()\n                        );\n                }\n                else {\n                    this.#tickMarkLayer.replaceChildren();\n                }\n            }\n            else {\n                this.#tickMarkLayer.replaceChildren();\n            }\n\n            this.#tickMarkLayer.appendChild(\n                fragment\n            );'''
if s.count(old)!=1: raise SystemExit(f'append block count {s.count(old)}')
s=s.replace(old,new,1)
p.write_text(s)
