from pathlib import Path
p=Path('TemporalFormat.js')
s=p.read_text()
s=s.replace('''    static #TIME_TOKENS = [\n        "hh",\n        "mm",\n        "ss",\n        "h"\n    ];''','''    static #TIME_TOKENS = [\n        "HH",\n        "hh",\n        "mm",\n        "ss",\n        "H",\n        "h"\n    ];''')
old='''        let hour =\n            date.getHours();\n\n        if (!militaryTime) {\n            hour %= 12;\n\n            if (hour === 0) {\n                hour = 12;\n            }\n        }\n\n        const values = {\n            hh: TemporalFormat.#pad(\n                hour,\n                2\n            ),\n            h: String(hour),\n            mm: TemporalFormat.#pad(\n                date.getMinutes(),\n                2\n            ),\n            ss: TemporalFormat.#pad(\n                date.getSeconds(),\n                2\n            )\n        };'''
new='''        const militaryHour =\n            date.getHours();\n\n        let standardHour =\n            militaryHour % 12;\n\n        if (standardHour === 0) {\n            standardHour = 12;\n        }\n\n        const values = {\n            HH: TemporalFormat.#pad(\n                militaryHour,\n                2\n            ),\n            H: String(militaryHour),\n            hh: TemporalFormat.#pad(\n                standardHour,\n                2\n            ),\n            h: String(standardHour),\n            mm: TemporalFormat.#pad(\n                date.getMinutes(),\n                2\n            ),\n            ss: TemporalFormat.#pad(\n                date.getSeconds(),\n                2\n            )\n        };'''
assert old in s
s=s.replace(old,new)
old2='''        const hasHour =\n            tokens.includes("h") ||\n            tokens.includes("hh");\n\n        if (\n            !hasHour ||\n            !tokens.includes("mm")\n        ) {\n            return undefined;\n        }\n\n        void militaryTime;\n\n        return text;'''
new2='''        const hasMilitaryHour =\n            tokens.includes("H") ||\n            tokens.includes("HH");\n\n        const hasStandardHour =\n            tokens.includes("h") ||\n            tokens.includes("hh");\n\n        const hasExpectedHour =\n            militaryTime\n                ? hasMilitaryHour\n                : hasStandardHour;\n\n        if (\n            !hasExpectedHour ||\n            hasMilitaryHour === hasStandardHour ||\n            !tokens.includes("mm")\n        ) {\n            return undefined;\n        }\n\n        return text;'''
assert old2 in s
s=s.replace(old2,new2)
p.write_text(s)
