from pathlib import Path

path = Path('ClockTimer.js')
text = path.read_text()
old = '''        #runSpin(rotations, duration) {\n            if (!this.#clockFace) {\n                return;\n            }\n\n            const perRotationDuration =\n                this.#getSpinDurationMilliseconds(\n                    duration\n                );\n\n            this.#spinAnimation\n                ?.cancel();\n\n            this.#spinAnimation =\n                this.#clockFace.animate(\n                    [\n                        {\n                            transform: \"rotateY(0deg)\"\n                        },\n                        {\n                            transform: `rotateY(${rotations * 360}deg)`\n                        }\n                    ],\n                    {\n                        duration:\n                            perRotationDuration *\n                            rotations,\n                        easing: \"ease-in-out\"\n                    }\n                );\n\n            this.#spinAnimation.finished\n                .catch(() => {})\n                .finally(() => {\n                    this.#spinAnimation =\n                        undefined;\n                });\n        }\n'''
new = '''        #runSpin(rotations, duration) {\n            const perRotationDuration =\n                this.#getSpinDurationMilliseconds(\n                    duration\n                );\n\n            this.#spinAnimation\n                ?.cancel();\n\n            this.#spinAnimation =\n                this.animate(\n                    [\n                        {\n                            transform: \"perspective(var(--clock-timer-spin-perspective, 800px)) rotateY(0deg)\"\n                        },\n                        {\n                            transform: `perspective(var(--clock-timer-spin-perspective, 800px)) rotateY(${rotations * 360}deg)`\n                        }\n                    ],\n                    {\n                        duration:\n                            perRotationDuration *\n                            rotations,\n                        easing: \"ease-in-out\"\n                    }\n                );\n\n            this.#spinAnimation.finished\n                .catch(() => {})\n                .finally(() => {\n                    this.#spinAnimation =\n                        undefined;\n                });\n        }\n'''
if old not in text:
    raise SystemExit('spin block not found')
text = text.replace(old, new, 1)
path.write_text(text)
