from pathlib import Path
p=Path('ClockTimer.js')
s=p.read_text()
old='''            const record =\n                this.#openEndedRange;\n\n            if (!record) {\n                return false;\n            }\n\n            const endDate =\n                this.#normalizeTickDate(\n                    new Date()\n                );\n'''
new='''            const insertRecord =\n                this.#openEndedRange;\n\n            const overwriteRecord =\n                this.#openOverwriteRange;\n\n            if (\n                !insertRecord &&\n                !overwriteRecord\n            ) {\n                return false;\n            }\n\n            const endDate =\n                this.#normalizeTickDate(\n                    new Date()\n                );\n\n            if (\n                !insertRecord &&\n                overwriteRecord\n            ) {\n                const endTimeline =\n                    this.#getCurrentTimelineTime(\n                        endDate\n                    );\n\n                this.#updateOpenOverwriteRange(\n                    endDate\n                );\n\n                overwriteRecord.openEnded =\n                    false;\n\n                overwriteRecord.end =\n                    Math.max(\n                        overwriteRecord.start,\n                        endTimeline\n                    );\n\n                this.#openOverwriteRange =\n                    undefined;\n\n                this.#openOverwriteLastTick =\n                    undefined;\n\n                this.#tickAlignmentMilliseconds =\n                    endDate.getMilliseconds();\n\n                if (this.#needsTick()) {\n                    this.#startTickTimer();\n                }\n                else {\n                    this.#stopTickTimer();\n                }\n\n                return true;\n            }\n\n            const record =\n                insertRecord;\n'''
if old not in s:
    raise SystemExit('target block not found')
s=s.replace(old,new,1)
p.write_text(s)
