from pathlib import Path

path = Path("ClockTimer.js")
text = path.read_text()

old_insert = '''            if (record.openEnded) {\n                const initialNow =\n                    new Date();\n\n                if (\n                    initialNow.getTime() <=\n                        record.startDate.getTime()\n                ) {\n                    initialNow.setTime(\n                        record.startDate.getTime() +\n                        1\n                    );\n                }\n\n                this.#updateOpenEndedRange(\n                    initialNow\n                );\n            }\n            else {\n                this.#renderAllInsertedRanges();\n            }\n\n            const insertedElement =\n                this.#getManagedTimeRanges()\n                    .find(\n                        candidate =>\n                            candidate.clockTimerInserted ===\n                                record.id\n                    );\n'''

new_insert = '''            let insertedElement;\n\n            if (record.openEnded) {\n                const initialNowDate =\n                    new Date();\n\n                let initialEnd =\n                    this.#dateToTimelineTime(\n                        initialNowDate\n                    );\n\n                if (initialEnd <= startTimeline) {\n                    initialEnd =\n                        startTimeline + 1;\n                }\n\n                const delta =\n                    initialEnd - startTimeline;\n\n                this.#extendCalculatedEndTime(\n                    delta,\n                    record.type\n                );\n\n                this.#openEndedLastTick =\n                    initialEnd;\n\n                this.#shiftRangesAfter(\n                    startTimeline,\n                    delta,\n                    record\n                );\n\n                const ring =\n                    this.#ensureRing(\n                        this.#getRingIndex(\n                            startTimeline\n                        )\n                    );\n\n                insertedElement =\n                    this.#createTimeRange(\n                        record.type,\n                        startTimeline,\n                        initialEnd,\n                        { dynamic: true }\n                    );\n\n                delete insertedElement.clockTimerDynamic;\n\n                insertedElement.clockTimerInserted =\n                    record.id;\n\n                this.#applyOtherAttributes(\n                    insertedElement,\n                    record.otherAttributes\n                );\n\n                ring.appendChild(\n                    insertedElement\n                );\n\n                this.#refreshRingLayout(\n                    this.#started\n                        ? this.#getCurrentTimelineTime()\n                        : startTimeline\n                );\n            }\n            else {\n                this.#renderAllInsertedRanges();\n\n                insertedElement =\n                    this.#getManagedTimeRanges()\n                        .find(\n                            candidate =>\n                                candidate.clockTimerInserted ===\n                                    record.id\n                        );\n            }\n'''

if old_insert not in text:
    raise SystemExit("open insert block not found")
text = text.replace(old_insert, new_insert, 1)

old_overwrite = '''                const initialNowDate =\n                    new Date();\n\n                let initialNow =\n                    this.#getCurrentTimelineTime(\n                        initialNowDate\n                    );\n\n                if (initialNow <= start) {\n                    initialNow =\n                        start + 1;\n                }\n\n                this.#updateOpenOverwriteRange(\n                    new Date(\n                        initialNowDate.getTime() +\n                        Math.max(\n                            0,\n                            initialNow -\n                                this.#getCurrentTimelineTime(\n                                    initialNowDate\n                                )\n                        )\n                    )\n                );\n\n                const overwriteElement =\n                    this.#getManagedTimeRanges()\n                        .find(\n                            candidate =>\n                                candidate.clockTimerOverwrite ===\n                                    record.id\n                        );\n'''

new_overwrite = '''                let initialEnd =\n                    this.#getCurrentTimelineTime();\n\n                if (initialEnd <= start) {\n                    initialEnd =\n                        start + 1;\n                }\n\n                const net =\n                    this.#getOverwriteCalculatedEndDelta(\n                        start,\n                        initialEnd,\n                        record.type\n                    );\n\n                this.#adjustCalculatedEndTime(\n                    net\n                );\n\n                this.#applyOverwriteMask(\n                    start,\n                    initialEnd\n                );\n\n                this.#openOverwriteLastTick =\n                    initialEnd;\n\n                record.end =\n                    initialEnd;\n\n                const ring =\n                    this.#ensureRing(\n                        this.#getRingIndex(\n                            start\n                        )\n                    );\n\n                const overwriteElement =\n                    this.#createTimeRange(\n                        record.type,\n                        start,\n                        initialEnd,\n                        { dynamic: true }\n                    );\n\n                delete overwriteElement.clockTimerDynamic;\n\n                overwriteElement.clockTimerOverwrite =\n                    record.id;\n\n                overwriteElement.timeRangeFullEntry =\n                    true;\n\n                ring.appendChild(\n                    overwriteElement\n                );\n'''

if old_overwrite not in text:
    raise SystemExit("open overwrite block not found")
text = text.replace(old_overwrite, new_overwrite, 1)

path.write_text(text)
