from pathlib import Path
p=Path('ClockTimer.js')
s=p.read_text()

def rep(old,new,count=1):
    global s
    if old not in s:
        raise SystemExit('missing anchor: '+old[:100])
    s=s.replace(old,new,count)

rep('''            "visible-hours",\n            "tick-marks"\n        ];''','''            "visible-hours",\n            "tick-marks",\n            "indicator-symbol"\n        ];''')
rep('''        #tickMarkLayer;\n\n        #tickMarkTimeout;''','''        #tickMarkLayer;\n\n        #indicatorRing;\n\n        #indicatorTrack;\n\n        #indicatorSymbol;\n\n        #indicatorFrame;\n\n        #indicatorStartFrame;\n\n        #tickMarkTimeout;''')
rep('''                #tick-marks,\n                #hand-layer {''','''                #tick-marks,\n                #hand-layer,\n                #indicator-ring {''')
rep('''                #time-layer {\n                    position: absolute;''','''                #indicator-ring {\n                    position: absolute;\n                    inset: 0;\n                    z-index: 25;\n                    pointer-events: none;\n                    opacity: 0;\n                    transition-property: opacity;\n                    transition-duration: var(--clock-timer-ring-resize-duration);\n                    transition-timing-function: linear;\n                }\n\n                #indicator-track {\n                    position: absolute;\n                    inset: 0;\n                    transform: rotate(0deg);\n                    transform-origin: 50% 50%;\n                    pointer-events: none;\n                }\n\n                #indicator-symbol {\n                    position: absolute;\n                    top: 0;\n                    left: 50%;\n                    display: block;\n                    width: max-content;\n                    height: max-content;\n                    line-height: 1;\n                    font-size: var(--clock-timer-indicator-symbol-size, 12px);\n                    color: currentColor;\n                    transform: translate(-50%, -100%);\n                    transform-origin: 50% 100%;\n                    pointer-events: none;\n                }\n\n                #indicator-symbol::before {\n                    content: var(--clock-timer-indicator-symbol-content, "▼");\n                }\n\n                #time-layer {\n                    position: absolute;''')
rep('''            this.#tickMarkLayer.setAttribute(\n                "part",\n                "tick-marks"\n            );\n\n            const timeLayer =''','''            this.#tickMarkLayer.setAttribute(\n                "part",\n                "tick-marks"\n            );\n\n            this.#indicatorRing =\n                document.createElement(\n                    "div"\n                );\n\n            this.#indicatorRing.id =\n                "indicator-ring";\n\n            this.#indicatorTrack =\n                document.createElement(\n                    "div"\n                );\n\n            this.#indicatorTrack.id =\n                "indicator-track";\n\n            this.#indicatorSymbol =\n                document.createElement(\n                    "span"\n                );\n\n            this.#indicatorSymbol.id =\n                "indicator-symbol";\n\n            this.#indicatorSymbol.setAttribute(\n                "part",\n                "indicator-symbol"\n            );\n\n            this.#indicatorTrack.appendChild(\n                this.#indicatorSymbol\n            );\n\n            this.#indicatorRing.appendChild(\n                this.#indicatorTrack\n            );\n\n            const timeLayer =''')
rep('''                ringLayer,\n                this.#tickMarkLayer,\n                this.#handLayer,''','''                ringLayer,\n                this.#tickMarkLayer,\n                this.#indicatorRing,\n                this.#handLayer,''')
rep('''            this.#stopSizeObserver();\n\n            if (''','''            this.#stopSizeObserver();\n\n            if (this.#indicatorFrame !== undefined) {\n                cancelAnimationFrame(this.#indicatorFrame);\n                this.#indicatorFrame = undefined;\n            }\n\n            if (this.#indicatorStartFrame !== undefined) {\n                cancelAnimationFrame(this.#indicatorStartFrame);\n                this.#indicatorStartFrame = undefined;\n            }\n\n            if (''',1)
rep('''                case "tick-marks":\n                    this.#updateTickMarks();\n                    break;\n            }''','''                case "tick-marks":\n                    this.#updateTickMarks();\n                    break;\n\n                case "indicator-symbol":\n                    this.#scheduleIndicatorSymbolUpdate();\n                    break;\n            }''')
rep('''            this.#starting =\n                true;\n\n            try {''','''            this.#setIndicatorSymbolVisible(false);\n\n            this.#starting =\n                true;\n\n            try {''')
rep('''            this.#animateStartedRingWidths();\n\n            this.#stopTickTimer();''','''            this.#animateStartedRingWidths();\n\n            if (this.#indicatorStartFrame !== undefined) {\n                cancelAnimationFrame(this.#indicatorStartFrame);\n            }\n\n            this.#indicatorStartFrame = requestAnimationFrame(() => {\n                this.#indicatorStartFrame = requestAnimationFrame(() => {\n                    this.#indicatorStartFrame = undefined;\n                    this.#updateIndicatorSymbol();\n                });\n            });\n\n            this.#stopTickTimer();''')
rep('''        clear() {\n            this.#stopTickTimer();''','''        clear() {\n            this.#stopTickTimer();\n            this.#setIndicatorSymbolVisible(false);''')
rep('''            this.#scheduleHourRender();\n\n            if (\n                !this.hasAttribute(\n                    "tick-marks"''','''            this.#scheduleHourRender();\n            this.#scheduleIndicatorSymbolUpdate();\n\n            if (\n                !this.hasAttribute(\n                    "tick-marks"''')
anchor='''        #needsTick() {\n'''
methods='''        #setIndicatorSymbolVisible(visible) {\n            if (!this.#indicatorRing) {\n                return;\n            }\n\n            this.#indicatorRing.style.opacity = visible ? "1" : "0";\n        }\n\n        #scheduleIndicatorSymbolUpdate() {\n            if (this.#indicatorFrame !== undefined) {\n                cancelAnimationFrame(this.#indicatorFrame);\n            }\n\n            this.#indicatorFrame = requestAnimationFrame(() => {\n                this.#indicatorFrame = undefined;\n                this.#updateIndicatorSymbol();\n            });\n        }\n\n        #updateIndicatorSymbol() {\n            if (!this.#indicatorRing || !this.#indicatorTrack || !this.#indicatorSymbol) {\n                return;\n            }\n\n            if (!this.hasAttribute("indicator-symbol") || !this.#started || !this.#elapsedRange) {\n                this.#setIndicatorSymbolVisible(false);\n                return;\n            }\n\n            const ring = this.#elapsedRange.parentElement;\n\n            if (!ring || ring.localName !== "ring-container" || !ring.hasAttribute("active")) {\n                this.#setIndicatorSymbolVisible(false);\n                return;\n            }\n\n            const end = Number(this.#elapsedRange.clockTimerEnd);\n            const ringIndex = Number(ring.clockTimerRingIndex);\n\n            if (!Number.isFinite(end) || !Number.isFinite(ringIndex)) {\n                this.#setIndicatorSymbolVisible(false);\n                return;\n            }\n\n            const ringStart = this.#getRingStart(ringIndex);\n            const angle = ((end - ringStart) / ClockTimer.#HOUR) * 360;\n            const normalizedAngle = (angle % 360 + 360) % 360;\n            const inset = ring.renderedInset ?? ring.inset ?? "0px";\n\n            this.#indicatorRing.style.inset = inset;\n            this.#indicatorTrack.style.transform = `rotate(${normalizedAngle}deg)`;\n            this.#setIndicatorSymbolVisible(!this.#starting);\n        }\n\n'''+anchor
rep(anchor,methods)
p.write_text(s)
