from pathlib import Path

clock_path = Path("ClockTimer.js")
app_path = Path("app.js")
clock = clock_path.read_text()
app = app_path.read_text()


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, found {count}")
    return text.replace(old, new, 1)


clock = replace_once(
    clock,
    '''        #emitClockTimerEvent(name, detail = {}, { cancelable = false } = {}) {\n''',
    '''        #getSemanticIntervalEventName(type, phase) {\n            const normalized =\n                String(type ?? "")\n                    .trim()\n                    .toLowerCase();\n\n            const names = {\n                break: {\n                    started: "breakStarted",\n                    ended: "breakEnded"\n                },\n                lunch: {\n                    started: "lunchStarted",\n                    ended: "lunchEnded"\n                },\n                down: {\n                    started: "downTimeStarted",\n                    ended: "downTimeEnded"\n                }\n            };\n\n            return names[normalized]?.[phase];\n        }\n\n        #getSemanticIntervalDetail(record, detail = {}) {\n            const attributes =\n                record?.otherAttributes &&\n                typeof record.otherAttributes === "object"\n                    ? { ...record.otherAttributes }\n                    : {};\n\n            let breakType;\n            for (const [name, value] of Object.entries(attributes)) {\n                if (name.toLowerCase() === "breaktype") {\n                    breakType = value;\n                    break;\n                }\n            }\n\n            return {\n                ...detail,\n                intervalType: record?.type,\n                breakType:\n                    breakType === undefined\n                        ? undefined\n                        : String(breakType),\n                attributes\n            };\n        }\n\n        #emitSemanticIntervalEvent(phase, record, detail = {}) {\n            const eventName =\n                this.#getSemanticIntervalEventName(\n                    record?.type,\n                    phase\n                );\n\n            if (!eventName) {\n                return true;\n            }\n\n            return this.#emitClockTimerEvent(\n                eventName,\n                this.#getSemanticIntervalDetail(\n                    record,\n                    detail\n                )\n            );\n        }\n\n        #emitClockTimerEvent(name, detail = {}, { cancelable = false } = {}) {\n''',
    "semantic helper insertion"
)

old_start = '''            this.#emitClockTimerEvent("intervalStarted", {\n                ...result,\n                type: record.type,\n                startTime: record.startDate?.toISOString?.(),\n                endTime: record.endDate?.toISOString?.(),\n                startBufferIntervalId:\n                    Number.isInteger(\n                        Number(\n                            startBufferRecord?.intervalId\n                        )\n                    )\n                        ? Number(\n                            startBufferRecord.intervalId\n                        )\n                        : undefined,\n                endBufferIntervalId:\n                    Number.isInteger(\n                        Number(\n                            endBufferRecord?.intervalId\n                        )\n                    )\n                        ? Number(\n                            endBufferRecord.intervalId\n                        )\n                        : undefined\n            });\n\n\n            if (\n                String(record.type).toLowerCase() === "down" &&\n                record.openEnded === true\n            ) {\n                this.#emitClockTimerEvent("downTimeStarted", {\n                    ...result,\n                    type: record.type,\n                    startTime: record.startDate?.toISOString?.(),\n                    endTime: undefined\n                });\n            }\n            return result;\n'''
new_start = '''            const intervalStartedDetail = {\n                ...result,\n                type: record.type,\n                startTime: record.startDate?.toISOString?.(),\n                endTime: record.endDate?.toISOString?.(),\n                startBufferIntervalId:\n                    Number.isInteger(\n                        Number(\n                            startBufferRecord?.intervalId\n                        )\n                    )\n                        ? Number(\n                            startBufferRecord.intervalId\n                        )\n                        : undefined,\n                endBufferIntervalId:\n                    Number.isInteger(\n                        Number(\n                            endBufferRecord?.intervalId\n                        )\n                    )\n                        ? Number(\n                            endBufferRecord.intervalId\n                        )\n                        : undefined\n            };\n\n            this.#emitClockTimerEvent(\n                "intervalStarted",\n                intervalStartedDetail\n            );\n\n            this.#emitSemanticIntervalEvent(\n                "started",\n                record,\n                intervalStartedDetail\n            );\n\n            return result;\n'''
clock = replace_once(clock, old_start, new_start, "interval started semantic event")

old_sched = '''            const endedEarly =\n                Number.isFinite(scheduledEnd) &&\n                now < scheduledEnd;\n'''
new_sched = '''            const lifecycleScheduledEnd =\n                record\n                    ? (\n                        Number.isFinite(\n                            Number(\n                                record.clockTimerExtensionOriginalEndTimeline\n                            )\n                        )\n                            ? Number(\n                                record.clockTimerExtensionOriginalEndTimeline\n                            )\n                            : this.#getIntervalRecordEnd(\n                                record\n                            )\n                    )\n                    : undefined;\n\n            const endedEarly =\n                Number.isFinite(scheduledEnd) &&\n                now < scheduledEnd;\n'''
clock = replace_once(clock, old_sched, new_sched, "lifecycle scheduled end")

old_end = '''            const result = this.#mutationResult(synced, record);\n            this.#checkGoalMisses(this.#getCurrentTimelineTime());\n            this.#emitClockTimerEvent("intervalEnded", {\n                ...result,\n                ...this.#getTimingDetail(\n                    now,\n                    scheduledEnd\n                ),\n                type: record?.type,\n                startTime: record?.startDate?.toISOString?.(),\n                endTime: record?.clockTimerPersistenceEnd ?? record?.endDate?.toISOString?.(),\n                actualEndTime:\n                    this.#timelineToISO(now),\n                scheduledEndTime:\n                    this.#timelineToISO(\n                        scheduledEnd\n                    )\n            });\n            return result;\n'''
new_end = '''            const result = this.#mutationResult(synced, record);\n            this.#checkGoalMisses(this.#getCurrentTimelineTime());\n\n            const intervalEndedDetail = {\n                ...result,\n                ...this.#getTimingDetail(\n                    now,\n                    scheduledEnd\n                ),\n                type: record?.type,\n                startTime: record?.startDate?.toISOString?.(),\n                endTime: record?.clockTimerPersistenceEnd ?? record?.endDate?.toISOString?.(),\n                actualEndTime:\n                    this.#timelineToISO(now),\n                scheduledEndTime:\n                    this.#timelineToISO(\n                        scheduledEnd\n                    ),\n                automaticRestart: false,\n                endReason: "manual"\n            };\n\n            this.#emitClockTimerEvent(\n                "intervalEnded",\n                intervalEndedDetail\n            );\n\n            const lifecycleTiming =\n                this.#getTimingDetail(\n                    now,\n                    lifecycleScheduledEnd\n                );\n\n            this.#emitSemanticIntervalEvent(\n                "ended",\n                record,\n                {\n                    ...intervalEndedDetail,\n                    ...lifecycleTiming,\n                    completion:\n                        lifecycleTiming.timing,\n                    scheduledEndTime:\n                        this.#timelineToISO(\n                            lifecycleScheduledEnd\n                        )\n                }\n            );\n\n            return result;\n'''
clock = replace_once(clock, old_end, new_end, "manual interval ended semantic event")

old_auto = '''            if (\n                this.#autoRestartTripAfterLateBreak &&\n                decision.boundaryType === "end-buffer" &&\n                ["break", "lunch"].includes(String(record.type).toLowerCase()) &&\n                this.#endPendingInterval(now)\n            ) {\n                this.#emitClockTimerEvent("tripAutomaticallyRestarted", {\n                    intervalId: Number.isInteger(Number(record.intervalId))\n                        ? Number(record.intervalId)\n                        : undefined,\n                    intervalType: record.type,\n                    boundaryType: decision.boundaryType,\n                    boundaryTime: this.#timelineToISO(boundary),\n                    restartTime: this.#timelineToISO(now)\n                });\n                return true;\n            }\n'''
new_auto = '''            if (\n                this.#autoRestartTripAfterLateBreak &&\n                decision.boundaryType === "end-buffer" &&\n                ["break", "lunch"].includes(String(record.type).toLowerCase())\n            ) {\n                const lifecycleScheduledEnd =\n                    Number.isFinite(\n                        Number(\n                            record.clockTimerExtensionOriginalEndTimeline\n                        )\n                    )\n                        ? Number(\n                            record.clockTimerExtensionOriginalEndTimeline\n                        )\n                        : this.#getIntervalRecordEnd(\n                            record\n                        );\n\n                if (this.#endPendingInterval(now)) {\n                    const lifecycleTiming =\n                        this.#getTimingDetail(\n                            now,\n                            lifecycleScheduledEnd\n                        );\n\n                    const intervalEndedDetail = {\n                        ...this.#mutationResult(\n                            false,\n                            record\n                        ),\n                        ...lifecycleTiming,\n                        completion:\n                            lifecycleTiming.timing,\n                        type: record.type,\n                        startTime:\n                            record.startDate?.toISOString?.(),\n                        endTime:\n                            this.#timelineToISO(now),\n                        actualEndTime:\n                            this.#timelineToISO(now),\n                        scheduledEndTime:\n                            this.#timelineToISO(\n                                lifecycleScheduledEnd\n                            ),\n                        automaticRestart: true,\n                        endReason: "automatic-restart"\n                    };\n\n                    this.#emitClockTimerEvent(\n                        "intervalEnded",\n                        intervalEndedDetail\n                    );\n\n                    this.#emitSemanticIntervalEvent(\n                        "ended",\n                        record,\n                        intervalEndedDetail\n                    );\n\n                    this.#emitClockTimerEvent("tripAutomaticallyRestarted", {\n                        intervalId: Number.isInteger(Number(record.intervalId))\n                            ? Number(record.intervalId)\n                            : undefined,\n                        intervalType: record.type,\n                        boundaryType: decision.boundaryType,\n                        boundaryTime: this.#timelineToISO(boundary),\n                        restartTime: this.#timelineToISO(now)\n                    });\n                    return true;\n                }\n            }\n'''
clock = replace_once(clock, old_auto, new_auto, "automatic break end lifecycle")

old_break_handler = '''    breakDialog.querySelectorAll("[data-break-type]").forEach(button => {\n        button.addEventListener("pointerup", () => {\n            void (async () => {\n                if (!await startBreakInterval(button.dataset.breakType)) return;\n                closeDialog(breakDialog, { reason: "break-type-selected" });\n            })().catch(() => {});\n        });\n    });\n'''
new_break_handler = '''    breakDialog.querySelectorAll("[data-break-type]").forEach(button => {\n        button.addEventListener("click", () => {\n            const startPromise =\n                startBreakInterval(\n                    button.dataset.breakType\n                );\n\n            closeDialog(\n                breakDialog,\n                { reason: "break-type-selected" }\n            );\n\n            void startPromise.catch(() => {});\n        });\n    });\n'''
app = replace_once(app, old_break_handler, new_break_handler, "break dialog activation")

old_break_result = '''        const result = await clockTimer.startInterval(\n            config.type,\n            config.length,\n            config.attributes,\n            "0:02:30",\n            "0:02:30"\n        );\n        if (result) renderTripActionState();\n        return Boolean(result);\n'''
new_break_result = '''        const result = await clockTimer.startInterval(\n            config.type,\n            config.length,\n            config.attributes,\n            "0:02:30",\n            "0:02:30"\n        );\n        return Boolean(result);\n'''
app = replace_once(app, old_break_result, new_break_result, "event-driven break UI")

clock_path.write_text(clock)
app_path.write_text(app)
