import fs from 'node:fs';import assert from 'node:assert/strict';import {Window} from 'happy-dom';
const w=new Window({url:'https://clock.example/'});w.eval(fs.readFileSync(new URL('../CalendarRange.js',import.meta.url),'utf8'));w.eval(fs.readFileSync(new URL('../TripLog.js',import.meta.url),'utf8'));
const root=w.document.createElement('div');w.document.body.append(root);let criteria='pay-period',filter='all',pad,includeCurrentSetting=false;
const events=[{id:1,event:'trip.started',timestamp:'2026-09-18 12:00:00',value:{}},{id:2,event:'interval.started',timestamp:'2026-09-18 12:05:00',value:{type:'break',length:'2:00',intervalKey:'b'}},{id:3,event:'interval.ended',timestamp:'2026-09-18 12:07:00',value:{intervalKey:'b'}},{id:4,event:'trip.stopped',timestamp:'2026-09-18 12:20:00',value:{}}];
const settings={creationAnchor:'2026-09-18T00:00:00Z',standardTime:'20:00',creationTime:'11:00:00',scheduledStart:'12:00:00',startTime:'12:00:00',nonProduction:false};
const view=new w.TripLog(root,{range:()=>criteria,filter:()=>filter,includeCurrent:()=>includeCurrentSetting,onIncludeCurrent:value=>{includeCurrentSetting=value;view.rerender();},onFilter:v=>filter=v,onRange:v=>criteria=v,onDate(){},numberPad:async options=>pad=options,request:async()=>({events,settings,revision:'test'}),refresh:async()=>{}});
const originalRequest=view.options.request;
const calendar={range:'pay-period',timezone:'UTC',startTime:'2026-09-05T00:00:00Z',endTime:'2026-09-19T00:00:00Z',rules:{weekStartDay:6,cutoffTime:'00:00:00'}};
const trips=[{id:2,startTime:'2026-09-17 09:00:00',endTime:'2026-09-17 09:30:00',standardTimeMilliseconds:1800000,actualTimeMilliseconds:1800000,events:[]},{id:1,startTime:'2026-09-18 12:00:00',endTime:'2026-09-18 12:20:00',standardTimeMilliseconds:1200000,actualTimeMilliseconds:1200000,events}];
view.render({trips},calendar);assert.equal(root.querySelector('.trip-log-trip summary strong').textContent,'12:00');assert(!root.textContent.includes('September 2026'));assert.equal(root.querySelectorAll('.trip-log-overview').length,1);assert(root.textContent.includes('Standard 0:50:00'));assert(root.querySelectorAll('.trip-log-group').length>=3);
assert.deepEqual([...root.querySelectorAll('.trip-log-column-header [role="columnheader"]')].map(cell=>cell.textContent),['Time','Standard','Actual','Percent','']);
assert.equal(w.TripLog.duration(27*3600000+5*60000+9000),'27:05:09');assert.equal(w.TripLog.percent([{standardTimeMilliseconds:100,actualTimeMilliseconds:100},{standardTimeMilliseconds:100,actualTimeMilliseconds:300}]),'50.0%');
assert.equal(w.TripLog.percent([{standardTimeMilliseconds:100,actualTimeMilliseconds:200,countedTimeMilliseconds:100}]),'100.0%');
assert.equal(w.TripLog.percent([{running:true,standardTimeMilliseconds:1200000,actualTimeMilliseconds:600000}]),'200.0%');
assert.equal(w.TripLog.percent([{running:true,standardTimeMilliseconds:1200000,actualTimeMilliseconds:1500000}]),'80.0%');
assert.equal(w.TripLog.percent([{standardTimeMilliseconds:1200000,actualTimeMilliseconds:600000}]),'200.0%');
assert.equal(w.TripLog.percent([{standardTimeMilliseconds:600000,actualTimeMilliseconds:600000},{running:true,standardTimeMilliseconds:1200000,actualTimeMilliseconds:600000}],true),'100.0%');
assert.equal(w.TripLog.percent([{standardTimeMilliseconds:600000,actualTimeMilliseconds:600000},{running:true,includeInParentPercent:true,standardTimeMilliseconds:1200000,actualTimeMilliseconds:600000}],true),'150.0%');
console.log('PASS newest-first, pay-period hierarchy, weighted percentages, and unlimited-hour overview');
const collapsed=root.querySelector('.trip-log-group');collapsed.open=false;collapsed.dispatchEvent(new w.Event('toggle'));
let includeActive=false;
view.options.liveTrip=()=>({...trips[1],running:true,activeState:'break',includeInParentPercent:includeCurrentSetting||includeActive,actualTimeMilliseconds:1200000,countedTimeMilliseconds:1200000});
view.render({trips},calendar);
assert.equal(root.querySelector('.trip-log-group').open,false);
assert(root.querySelector('.trip-log-trip.is-active-trip'));
assert(root.querySelectorAll('.trip-log-group.has-active-trip').length>=2);
assert.equal(root.querySelector('.trip-log-trip.is-active-trip').dataset.activeState,'break');
assert.equal(root.querySelector('.trip-log-trip.is-active-trip .trip-log-menu'),null);
assert([...root.querySelectorAll('.trip-log-group.has-active-trip')].every(group=>group.dataset.activeState==='break'));
assert.equal(root.querySelector('.trip-log-entry.is-active-entry').dataset.activeState,'break');
assert.equal(root.querySelector('.trip-log-trip.is-active-trip>summary span:nth-of-type(2)').textContent,'0:20:00');
assert.equal(root.querySelector('.trip-log-overview .trip-log-times').textContent,'Standard 0:30:00 · Actual 0:30:00');
includeActive=true;view.render({trips},calendar);
assert.equal(root.querySelector('.trip-log-overview .trip-log-times').textContent,'Standard 0:50:00 · Actual 0:50:00');
includeActive=false;const includeCurrent=root.querySelector('[data-include-current]');includeCurrent.checked=true;includeCurrent.dispatchEvent(new w.Event('change'));assert.equal(root.querySelector('.trip-log-overview .trip-log-times').textContent,'Standard 0:50:00 · Actual 0:50:00');
const firstSweepDelay=root.querySelector('.trip-log-trip.is-active-trip').style.getPropertyValue('--trip-log-active-sweep-delay');
assert.match(firstSweepDelay,/^-\d+ms$/);
assert.equal(root.querySelector('.trip-log-group.has-active-trip').style.getPropertyValue('--trip-log-active-sweep-delay'),firstSweepDelay);
view.options.liveTrip=undefined;
console.log('PASS collapsed headers retain state while active trip values and parent activity markers update');
assert.equal(root.querySelector('.trip-log-settings').getAttribute('aria-hidden'),'true');
assert(root.querySelector('.trip-log-settings-content').inert);
view.setSettingsVisible(true);
assert(root.querySelector('.trip-log-settings').classList.contains('is-open'));
assert(!root.querySelector('.trip-log-settings-content').inert);
assert(root.querySelector('.trip-log-settings hr'));
const settingsNode=root.querySelector('.trip-log-settings');
const selectNode=root.querySelector('.trip-log-settings select');
selectNode.focus();
view.render({trips},calendar);
assert.equal(root.querySelector('.trip-log-settings'),settingsNode);
assert.equal(root.querySelector('.trip-log-settings select'),selectNode);
assert.equal(w.document.activeElement,selectNode);
assert(root.querySelector('.trip-log-settings').classList.contains('is-open'));
view.setSettingsVisible(false);
assert(root.querySelector('.trip-log-settings-content').inert);
console.log('PASS settings default hidden, toggle with divider, and remain open across data refreshes');
const dates=root.querySelectorAll('input[type=date]');assert.equal(dates[0].value,'2026-09-05');assert.equal(dates[1].value,'2026-09-18');assert(dates[0].disabled);
criteria='custom';view.render({trips},calendar);assert(!root.querySelector('input[type=date]').disabled);
await view.openSettings(trips[1]);assert(view.editor.textContent.includes('Scheduled start'));assert(view.editor.textContent.includes('Productive'));view.editor.close();
console.log('PASS shared date controls and trip settings editor');
view.render({trips:[]},calendar);
assert.equal(root.querySelector('.trip-log-overview'),null);
assert.equal(root.querySelector('.trip-log-column-header'),null);
assert(root.classList.contains('trip-log-empty'));
assert.equal(root.querySelector('.trip-log-empty-message').textContent,'No trips in this range.');
view.setSettingsVisible(true);
assert(root.querySelector('.trip-log-settings').classList.contains('is-open'));
view.render({trips},calendar);
assert(!root.classList.contains('trip-log-empty'));
assert(root.querySelector('.trip-log-overview'));
assert.equal(root.querySelector('.trip-log-empty-message'),null);
view.render({trips:[],loginRequired:true},calendar);
assert.equal(root.querySelector('.trip-log-overview'),null);
assert.equal(root.querySelector('.trip-log-empty-message').textContent,'Log in to view saved trips.');
assert(root.querySelector('.trip-log-settings select'));
console.log('PASS empty range replaces overview with centered message and restores summary when trips return');
view.render({trips:[{...trips[0],id:'offline-one',buffered:true},{...trips[1],id:'offline-two',buffered:true}],offline:true,incomplete:true},calendar);
assert.equal(root.querySelectorAll('.trip-log-trip').length,2);
assert(root.querySelector('.trip-log-overview .calculation-uncertain-icon'));
assert.equal(root.querySelectorAll('.trip-log-trip .trip-log-menu').length,2);
const localEvents=events.map((event,index)=>({...event,id:`local-${index}`})),offlineTrip={...trips[1],id:'offline-two',buffered:true,events:localEvents};
const offlineChanges=[];view.options.request=async(id,change)=>{if(change)offlineChanges.push(change);return {events:localEvents,settings,revision:'offline'};};view.options.refresh=async()=>{};
view.render({trips:[offlineTrip],offline:true,incomplete:true},calendar);
await view.beginEntryEdit(offlineTrip);
assert.match(root.querySelector('.trip-log-entries>p').textContent,/Swipe an interval.*Long-press an entry/);root.querySelector('.trip-log-entry-time').click();await new Promise(resolve=>setTimeout(resolve,10));assert.equal(pad.title,'Entry Time');assert(root.querySelector('.trip-log-add').hidden);await pad.onConfirm('2026-09-18T12:01:00Z');assert.equal(offlineChanges.length,0);assert.equal(view.trips[0].events[0].timestamp,'2026-09-18T12:01:00Z');assert(!root.querySelector('.trip-log-add').hidden);
const nameButton=root.querySelector('.trip-log-entry-name');nameButton.click();const inlineSelect=root.querySelector('.trip-log-entry>select');assert(inlineSelect);assert(![...inlineSelect.options].some(option=>option.textContent==='Cancel'));assert(root.querySelector('.trip-log-entry-cancel'));assert(root.querySelector('.trip-log-add').hidden);root.querySelector('.trip-log-entry-cancel').click();assert(root.querySelector('.trip-log-entry-name'));assert(root.querySelector('.trip-log-entries').lastElementChild.classList.contains('trip-log-add'));
let intervalRow=[...root.querySelectorAll('.trip-log-entry')].find(row=>row.textContent.includes('break'));const entryPress=new w.PointerEvent('pointerdown',{clientX:50,clientY:10,cancelable:true});intervalRow.dispatchEvent(entryPress);assert(entryPress.defaultPrevented);await new Promise(resolve=>setTimeout(resolve,600));
let add=root.querySelector('.trip-log-add');assert(add);assert.equal(add.nextElementSibling.textContent,intervalRow.textContent);add.click();assert.equal(root.querySelector('.trip-log-add'),null);let draft=root.querySelector('.trip-log-new-entry');assert(draft);assert.equal(draft.querySelector('.trip-log-entry-time').textContent,'---');assert(![...draft.querySelectorAll('option')].some(option=>option.textContent==='Cancel'));assert(draft.querySelector('.trip-log-entry-cancel'));
let newType=draft.querySelector('select');newType.value='break';newType.dispatchEvent(new w.Event('change'));draft=root.querySelector('.trip-log-new-entry');draft.querySelector('.trip-log-entry-time').click();await new Promise(resolve=>setTimeout(resolve,10));assert.equal(pad.mode,'absolute');assert.equal(pad.title,'Entry Time');await pad.onConfirm('2026-09-18T12:08:00Z');assert.equal(offlineChanges.length,0);assert.equal(root.querySelector('.trip-log-new-entry'),null);assert(root.querySelector('.trip-log-entries').lastElementChild.classList.contains('trip-log-add'));
intervalRow=[...root.querySelectorAll('.trip-log-entry')].find(row=>row.textContent.includes('break'));intervalRow.dispatchEvent(new w.PointerEvent('pointerdown',{clientX:50,clientY:10}));await new Promise(resolve=>setTimeout(resolve,600));root.querySelector('.trip-log-add').click();root.querySelector('.trip-log-new-entry .trip-log-entry-cancel').click();assert.equal(root.querySelector('.trip-log-new-entry'),null);assert(root.querySelector('.trip-log-entries').lastElementChild.classList.contains('trip-log-add'));
intervalRow=[...root.querySelectorAll('.trip-log-entry')].find(row=>row.textContent.includes('break')&&!row.classList.contains('trip-log-new-entry'));intervalRow.dispatchEvent(new w.PointerEvent('pointerdown',{clientX:100,clientY:10}));intervalRow.dispatchEvent(new w.PointerEvent('pointerup',{clientX:20,clientY:12}));await new Promise(resolve=>setTimeout(resolve,10));assert.equal(offlineChanges.length,0);
assert.equal(view.entryChanges(view.trips[0]).map(change=>change.operation).sort().join(','),'add-entry,delete-entry,entry');
root.querySelector('.trip-log-entry-heading button').click();await new Promise(resolve=>setTimeout(resolve,10));assert.equal(offlineChanges.length,1);assert.equal(offlineChanges[0].operation,'entries');assert.equal(offlineChanges[0].changes.map(change=>change.operation).sort().join(','),'add-entry,delete-entry,entry');assert(!view.editing.has('offline-two'));
offlineTrip.events=localEvents;view.render({trips:[offlineTrip],offline:true,incomplete:true},calendar);view.options.request=async(id,change)=>{if(change)throw new Error('Invalid draft');return {events:localEvents,settings,revision:'offline'};};await view.beginEntryEdit(offlineTrip);root.querySelector('.trip-log-entry-time').click();await new Promise(resolve=>setTimeout(resolve,10));assert.equal(pad.allowEmpty,true);await pad.onConfirm(undefined);assert.equal(root.querySelector('.trip-log-entry-time').textContent,'---');root.querySelector('.trip-log-entry-heading button').click();await new Promise(resolve=>setTimeout(resolve,10));assert(!view.editing.has('offline-two'));assert.equal(view.trips[0].events[0].timestamp,localEvents[0].timestamp);assert.equal(root.querySelector(':scope>.trip-log-error').textContent,'Invalid draft');root.querySelector(':scope>.trip-log-error').remove();
view.error(new Error('first'));view.error(new Error('replacement'));assert.equal(root.querySelectorAll(':scope>.trip-log-error').length,1);assert.equal(root.querySelector(':scope>.trip-log-error').textContent,'replacement');root.querySelector(':scope>.trip-log-error').remove();
view.options.request=originalRequest;
console.log('PASS offline entry editing, long-press insertion, cancellation, swipe deletion, and transient errors work');
view.setSettingsVisible(false);
view.render({trips:[],offline:true},calendar);
assert.match(root.querySelector('.trip-log-empty-message').textContent,/Connect to load saved trips/);
assert(root.querySelector('.trip-log-settings').classList.contains('is-open'));
view.render({trips:[trips[0]]},calendar);view.setSettingsVisible(false);
w.confirm=()=>true;
view.options.refresh=async()=>view.render({trips:[]},calendar);
await view.deleteTrip(trips[0]);
assert.equal(root.querySelector('.trip-log-overview'),null);
assert(root.querySelector('.trip-log-settings').classList.contains('is-open'));
console.log('PASS local offline trips and uncertain totals render, and deleting the only trip reveals filters');
w.happyDOM.abort();
